services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: "src-redis-1"
      REDIS_PORT: 6379
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "8001:8001"
      - "6379:6379"